version: "3.5"
services:
  apiserver:
    build: ./apiserver
    container_name: apiserver
    ports:
      - "3000:3000"
    command: /bin/sh -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
       - ./apiserver:/myapp
    depends_on:
      - database
    networks:
      - ducktail-network

  frontend:
    build: ./frontend-react
    container_name: frontend
    command: yarn start
    volumes:
      - ./frontend-react:/myapp
    ports:
      - 8000:3000
    networks:
      - ducktail-network

  database:
    image: postgres:10
    container_name: "database"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    networks:
      - ducktail-network

volumes:
  database:
    driver: local

networks:
  ducktail-network:
    name: ducktail-network
